/* Public files contain only opaque slots (s1...s7), never real model names. */
const STORAGE_KEY = "blind-photo-vote-v2";
const LABELS = ["A", "B", "C", "D", "E", "F", "G"];
let questions = [], index = 0, selections = new Set(), order = [], startedAt = 0, db = null;
let state = JSON.parse(localStorage.getItem(STORAGE_KEY) || '{"votes":{},"participantId":null}');
if (!state.participantId) { state.participantId = crypto.randomUUID(); persist(); }
function persist() { localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }
function shuffle(items) { const a = [...items]; for (let i=a.length-1;i>0;i--) { const j=crypto.getRandomValues(new Uint32Array(1))[0]%(i+1); [a[i],a[j]]=[a[j],a[i]]; } return a; }
function current() { return questions[index]; }
function configured() { return window.SUPABASE_CONFIG?.url?.startsWith("https://") && !window.SUPABASE_CONFIG?.anonKey?.includes("PASTE_"); }
function pendingVotes() { return Object.values(state.votes).filter(v => v.syncStatus !== "synced"); }
function setSyncStatus(text, tone="") { const el=document.querySelector('#syncStatus'); if(el) { el.textContent=text; el.className=`sync-status ${tone}`; } }
async function setupSupabase() {
  if (!configured()) { setSyncStatus("Supabase not set up: Votes are only saved locally and can be downloaded as a CSV.", "warn"); return; }
  db=window.supabase.createClient(window.SUPABASE_CONFIG.url, window.SUPABASE_CONFIG.anonKey);
  const {data}=await db.auth.getSession(); if (!data.session) { const {error}=await db.auth.signInAnonymously(); if(error) throw error; }
  setSyncStatus("Connected to the secure voting backend.", "ok");
}
function displayOrder(q) { return shuffle(q.candidates).map((candidate,i)=>({...candidate,label:LABELS[i]})); }
function render() {
  const q=current(); if(!q) { document.querySelector('#app').hidden=true; document.querySelector('#complete').hidden=false; updateCompleteMessage(); return; }
  selections=new Set(state.votes[q.id]?.selectedSlots||[]); order=displayOrder(q); startedAt=performance.now();
  document.querySelector('#questionId').textContent=` · question ${q.id}`; document.querySelector('#progressText').textContent=`Progress ${index+1} / ${questions.length}`; document.querySelector('#progressBar').style.width=`${index/questions.length*100}%`;
  document.querySelector('#originalImage').src=q.original; document.querySelector('#originalImage').alt=`The original image of question ${q.id} `;
  const box=document.querySelector('#choices'); box.innerHTML='';
  for(const c of order) { const card=document.createElement('article'); card.className='choice'+(selections.has(c.slot)?' selected':''); card.tabIndex=0; card.setAttribute('role','button'); card.innerHTML=`<div class="choice-label"><span>Candidate option ${c.label}</span><span class="rank">${selections.has(c.slot)?'Selected':'Select'}</span></div><img src="${c.image}" alt="Candidate option ${c.label}" loading="eager">`; const toggle=()=>{if(selections.has(c.slot))selections.delete(c.slot);else if(selections.size<2)selections.add(c.slot);updateCards();}; card.onclick=toggle; card.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();toggle();}}; box.append(card); }
  updateCards(); document.querySelector('#prevBtn').disabled=index===0;
}
function updateCards() { document.querySelectorAll('.choice').forEach((node,i)=>{const picked=selections.has(order[i].slot);node.classList.toggle('selected',picked);node.querySelector('.rank').textContent=picked?'Selected':'Choice';}); document.querySelector('#selectionStatus').textContent=`Selected ${selections.size} / 2`;document.querySelector('#nextBtn').disabled=selections.size!==2; }
async function syncVote(vote) { if(!db)return {ok:false,message:"Not configured in the backend"}; const {error}=await db.from('votes').insert({participant_id:state.participantId,question_id:vote.questionId,selected_slot_1:vote.selectedSlots[0],selected_slot_2:vote.selectedSlots[1],shown_order:vote.shownOrder,elapsed_seconds:vote.elapsedSeconds,client_saved_at:vote.savedAt}); if(error&&error.code!=='23505')return {ok:false,message:error.message};return {ok:true}; }
async function saveAndAdvance() { const q=current();const vote={questionId:q.id,selectedSlots:[...selections],shownOrder:order.map(x=>({label:x.label,slot:x.slot})),elapsedSeconds:Math.round((performance.now()-startedAt)/1000),savedAt:new Date().toISOString(),syncStatus:"pending"}; state.votes[q.id]=vote;persist();document.querySelector('#nextBtn').disabled=true;setSyncStatus("Uploading votes for this question…");try{const r=await syncVote(vote);vote.syncStatus=r.ok?"synced":"failed";vote.syncError=r.message||null;setSyncStatus(r.ok?"This question has been safely uploaded.":"Upload failed, saved locally; you can try uploading again later.",r.ok?"ok":"warn");}catch{vote.syncStatus="failed";setSyncStatus("Network error, your vote has been saved locally; you can upload it later.","warn");}persist();index++;render(); }
async function syncPending() { const items=pendingVotes();if(!items.length){setSyncStatus("All local votes have been uploaded.","ok");updateCompleteMessage();return;}if(!db){setSyncStatus("Supabase isn't set up yet, so you can't upload online.","warn");return;}setSyncStatus(`Uploading ${items.length} local records…`);for(const v of items){const r=await syncVote(v);v.syncStatus=r.ok?"synced":"failed";v.syncError=r.message||null;}persist();const n=pendingVotes().length;setSyncStatus(n?`${n} records failed to upload, please check your network and try again.`:"All the votes have been uploaded.",n?"warn":"ok");updateCompleteMessage(); }
function updateCompleteMessage(){const n=pendingVotes().length;document.querySelector('#completeMessage').textContent=n?`${n} options are still on this device. Click 'Re-upload' or download the CSV backup.`:"All choices have been successfully uploaded. You can also download the CSV to keep a copy.";}
function csvCell(v){return `"${String(v??'').replaceAll('"','""')}"`;}
function exportCsv(){const rows=[["participant_id","question_id","selected_slot_1","selected_slot_2","shown_label_slot_map","elapsed_seconds","saved_at","sync_status"]];for(const q of questions){const v=state.votes[q.id];if(v)rows.push([state.participantId,v.questionId,v.selectedSlots[0],v.selectedSlots[1],JSON.stringify(v.shownOrder),v.elapsedSeconds,v.savedAt,v.syncStatus]);}const blob=new Blob([rows.map(r=>r.map(csvCell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'});const a=Object.assign(document.createElement('a'),{href:URL.createObjectURL(blob),download:`blind-vote-${state.participantId.slice(0,8)}.csv`});a.click();URL.revokeObjectURL(a.href);}
document.querySelector('#nextBtn').onclick=saveAndAdvance;document.querySelector('#prevBtn').onclick=()=>{if(index){index--;render();}};document.querySelector('#syncBtn').onclick=syncPending;document.querySelector('#syncCompleteBtn').onclick=syncPending;document.querySelector('#exportBtn').onclick=exportCsv;document.querySelector('#exportCompleteBtn').onclick=exportCsv;document.querySelector('#resetBtn').onclick=()=>{if(confirm('Are you sure you want to clear all the votes saved on this device?')){localStorage.removeItem(STORAGE_KEY);location.reload();}};
fetch('questions.json').then(r=>{if(!r.ok)throw new Error(`Can't read questions.json (${r.status})`);return r.json();}).then(async data=>{questions=shuffle(data);document.querySelector('#loading').hidden=true;document.querySelector('#app').hidden=false;try{await setupSupabase();}catch(e){setSyncStatus(`Failed to connect to the backend：${e.message}；The vote will still be saved on this device.`,"warn");}render();}).catch(e=>{document.querySelector('#loading').hidden=true;const el=document.querySelector('#error');el.hidden=false;el.textContent=`Loading failed：${e.message}`;});
